apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    app: {{ include "app-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-chart.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "{{ .Values.db.host }}"
            - name: DB_PORT
              value: "{{ .Values.db.port }}"
            - name: DB_USER
              value: "{{ .Values.db.user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.db.password }}"
            - name: DB_NAME
              value: "{{ .Values.db.name }}"

